### PR TITLE
feat: add rustrover support

### PR DESCRIPTION
**Pull request by Azn9**
The apps I created are already part of a team so I cannot transfer you the ownership individually, if you want I can add you to it or let you recreate them, as you prefer (there is also another new IDE that will need to be added)

### CODE REVIEW

**Comment by Almighty-Alpaca** [comment]
> there is also another new IDE that will need to be added

I think there are two additional ones missing currently: Aqua and Writerside

The number of applications is slowly getting out of hand...

**Comment by Azn9** [comment]
> > there is also another new IDE that will need to be added
> 
> I think there are two additional ones missing currently: Aqua and Writerside
> 
> The number of applications is slowly getting out of hand...

Yep

I have a solution to solve (partially) the application amount issue, but it will need some time before working. Now you can send any image for the client to use as RPC assets, you don't need to upload them to the dev portal. I already planned to add two features related to that :
- the ability for the used to provide their own appid
- the ability for the user to use the project icon as the large image 

We can use this feature to only have one appid per IDE, instead of one per IDE per theme.

**Comment by Almighty-Alpaca** [comment]
> Now you can send any image for the client to use as RPC assets, you don't need to upload them to the dev portal.

This finally works??? I asked for that feature almost 6 years ago...

**Comment by Almighty-Alpaca** [comment]
Is there any documentation of this? It doesn't seem to be [here](https://discord.com/developers/docs/topics/rpc#setactivity) not does it seem to be supported by [GameSDK](https://discord.com/developers/docs/game-sdk/activities#updateactivity)

**Comment by Azn9** [comment]
@Almighty-Alpaca https://discord.com/developers/docs/rich-presence/faq#q-can-i-send-images-via-the-payload-rather-than-uploading-them-to-my-developer-dashboard
You can just pass a URL instead of an asset id

**Comment by Azn9** [comment]
For instance : https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/blob/master/main.cc#L158C21-L158C21

**Comment by Almighty-Alpaca** [comment]
Ah nice, then we'd just need to host the images somewhere. Maybe `raw.githubusercontent.com` (although you shouldn't use that as CND afaik) or GitHub Pages would be enough for this.

Although I would postpone that until later as it's a bigger rework of how images are served

**Pull request merged**
